name: Update Websites

# Controls when the action will run.
on:
    # Triggers the workflow on push events, but only for the master branch
    push:
        branches: [master]
        paths: ['docs/**']


    # Allows manually triggering the workflow from the Github Actions tab,
    # or from other repositories containing documentation updates
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

    # The workflow name
    websites-update:

        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:

            - name: Trigger Blackboard Workflow
              uses: benc-uk/workflow-dispatch@v1
              with:
                workflow: Build and Deploy Website
                repo: cfa-thestudio/thestudio-blackboard
                token: ${{ secrets.GIT_TOKEN }}

            - name: Trigger Whiteboard Workflow
              uses: benc-uk/workflow-dispatch@v1
              with:
                workflow: Build and Deploy Website
                repo: cfa-thestudio/thestudio-whiteboard
                token: ${{ secrets.GIT_TOKEN }}
